# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  BINARY_NAME: nmr

tasks:
  build:
    desc: Build binary
    cmds:
      - go build -o bin/{{.BINARY_NAME}}
  install:
      cmds:
        - go build -o {{.GOPATH}}/bin/nmr .
      vars:
        GOPATH:
          sh: go env GOPATH
